### ISSUE TITLE
Version 3 epic

### ISSUE THREAD

**Issue by NikolayRys** [NikolayRys/Likely#163]
## Features:
- [ ] Native share button https://github.com/NikolayRys/Likely/issues/156
- [x] In-text stylization(on @sashotoster)
- [x] Accessibility: https://github.com/NikolayRys/Likely/issues/161
- [ ] Document vertical alignment https://github.com/NikolayRys/Likely/issues/72
- [x] Remove counter separator https://github.com/NikolayRys/Likely/issues/125
- [x] Custom buttons support
- [x] Make clickable <divs> into buttons
- [ ] Add option to not appear until counters are fetched

## Tech: 
- [x] Remove likely() in favor of likely.initiate() (see #82 (comment)). And constructor.
- [x] Join .likely_visible and .likely_ready into a single class: it’s unclear why they are ever separate. (This could probably be a large breaking change because people can rely on one of these classes.) And remove the deprecation warning.
- [x] Bundle both JS and CSS into one file. This will let us get rid of Gulp and switch to Webpack completely.
- [x] Change interpretation of attributes: https://github.com/NikolayRys/Likely/issues/172 
- [x] Add contributing guidelines https://github.com/NikolayRys/Likely/issues/17
- [x] SVG icon strings encode SVG paths but omit the M letter in the code. This causes issues when contributors submit PRs providing this button (e.g. #101)

**Comment by vitkarpov** [comment]
> Join .likely_visible and .likely_ready into a single class

I'd suggest adding a deprecation warning first, like "We're going to remove timeout option and ready modifier at all. Please, file an issue if you know a good reason to not" in `v3.0` and see who's going to file an issue.

**Comment by NikolayRys** [comment]
You are right, this actually might be a good reason to move some of the features into 2.5, let me think a bit which ones.

**Comment by NikolayRys** [comment]
Decided to keep `.likely_visible` and `.likely_ready`.

**Comment by NikolayRys** [comment]
Note for self: review old branches if they contain anything worth considering

**Comment by NikolayRys** [comment]
Now tracked separaterly
