### ISSUE TITLE
Version 2.5 epic

### ISSUE THREAD

**Issue by NikolayRys** [NikolayRys/Likely#173]
## Tech: 
- [x] Fix erratic test and internal refactor: #168 - on me
- [x] Update dependencies: https://github.com/NikolayRys/Likely/pull/157 and https://github.com/NikolayRys/Likely/issues/159
- [x] Add `min` to built files https://github.com/NikolayRys/Likely/issues/149 and #165 
- [x] Proofread and clean up the readme. https://github.com/NikolayRys/Likely/issues/177
- [x] Cleanup redundant styles. https://github.com/NikolayRys/Likely/pull/175
- [x] Fix Travis CI #176 

## Features:
- [x] Re-initialization feature: https://github.com/NikolayRys/Likely/pull/162 
- [x] Viber support https://github.com/NikolayRys/Likely/issues/146
- [x] Bring back disabling of counters. https://github.com/NikolayRys/Likely/issues/145
- [x] Reddit button https://github.com/NikolayRys/Likely/issues/147 and #164 
- [x] Deprecate interpretation of attributes: https://github.com/NikolayRys/Likely/issues/172 
- [x] Deprecate different .likely_visible and .likely_ready - before joining them in 3.0.
- [x] Remove build artifacts and update release script https://github.com/NikolayRys/Likely/pull/178

**Comment by optimist-law** [comment]
Hello! If possible, increase the size of the Viber icon as WhatsApp (https://prnt.sc/sha3nb). Respectfully yours, Pavel

**Comment by NikolayRys** [comment]
@optimist-law nice catch, thank you.

@sashotoster Would you like to take a look? :)

**Comment by optimist-law** [comment]
> @optimist-law nice catch, thank you.
> 
> @sashotoster Would you like to take a look? :)

Yes

**Comment by NikolayRys** [comment]
@optimist-law I'm sorry, but what do you mean by that? To which line are you responding?

**Comment by NikolayRys** [comment]
The point "Deprecate different .likely_visible and .likely_ready - before joining them in 3.0." has been removed. Those fields have distinct and meaningful purpose. `likely_visible` appears when the buttons are instantiated, and `likely_ready` when the counters are.

**Comment by NikolayRys** [comment]
The version has been released.

**Comment by vitkarpov** [comment]
🎉
