### ISSUE TITLE
Long-term project improvements

### ISSUE THREAD

**Issue by iamakulov** [NikolayRys/Likely#31]
The project doesn’t correspond to the open-source quality defaults. Let’s make it better.
- [x] Specify safe semver ranges for dependencies (PR #42)
- [ ] Add `.editorconfig`
- [ ] Add contributing.md (issue #17)
- [x] Add linting for JavaScript (issue #28, PR #29)
- [ ] Add linting for Stylus files
- [x] Configure the Travis CI (issue #30, PR #39)
- [x] Update the project structure (issue #32, PR #141)
- [x] Add automated tests (PR #73)
- [ ] Improve the code (refactoring and related stuff) (issue #120)

**Comment by ilyabirman** [comment]
LICENSE? No way. This is not “quality defaults”, it’s stupid-as-fuck tradition.

Same with CONTRIBUTING.md. Only contributing.md.

**Comment by iamakulov** [comment]
@ilyabirman I agree that uppercase is stupid, but it’s a common convention, and literally every or almost every popular repository name the files this way. If we name them another way, contributors will have hard time finding them in our repo. I say this from my own contribution experience.

Also, `README.md` instead of `readme.md` (#32).

**Comment by sapegin** [comment]
You don’t have to follow this stupid tradition ;–) I always use normal names: `Readme.md`, `License.md`, etc., and I don’t believe that they are harder to find.

**Comment by iamakulov** [comment]
Capitalized names look OK for me.

**Comment by ilyabirman** [comment]
This tradition is downright unacceptable, we’ll have to break it. Sanity must win. No uppercase, sorry.

**Comment by iamakulov** [comment]
@ilyabirman OK. Are capitalized names appropriate? They still are more noticeable than the lowercased versions.

**Comment by vitkarpov** [comment]
@sapegin @ilyabirman guys, what's wrong with the `licence` file? I'm not against what Ilya's [said](https://github.com/ilyabirman/Likely/issues/31#issuecomment-217371565) but I'm just curious.

**Comment by sapegin** [comment]
@vitkarpov `licence` is fine (but `Licence` is better), `LICENSE` is terrible.

**Comment by vitkarpov** [comment]
Oh, I didn't get it right. I thought it's about the file itself, not the naming.

**Comment by iamakulov** [comment]
Added a new point:

> - [ ] Remove the built sources from the `release` directory and add a readme with the download links (for the users who are used to getting Likely from this directory)

**Comment by ilyabirman** [comment]
Why?

**Comment by ilyabirman** [comment]
All files should have extensions, no files should use caps lock. Sanity is above tradition.

I need to understand the reason behind every change in folder structure.

**Comment by iamakulov** [comment]
> Why?

Because maintaining it requires resources. We have to be careful enough to not commit `likely.js` and `likely.css` accidentally – they’re updated every time we build project, and it happens very often during the development. Some contributors include the built files into their PRs, and we have to ask them to revert these changes (https://github.com/ilyabirman/Likely/pull/23#issuecomment-216560329).

On the other hand: dropping the `release` dir will also mean dropping Bower support. I personally support this (Bower [stopped active development in 2014](https://github.com/bower/bower/graphs/contributors) and is getting less and less popular in favor of npm), however, we have a lot of non-frontend-savvy users which could still use Bower for their work. You know, I’d rather not drop it yet. So, well, removing this point.

**Comment by iamakulov** [comment]
You know, I’d rather not drop Bower yet. So, well, removing this point.

**Comment by iamakulov** [comment]
> I need to understand the reason behind every change in folder structure.

Let’s move the discussion to #32.

**Comment by iamakulov** [comment]
Added:

> - [ ] Improve the code (refactoring and related stuff)

**Comment by NikolayRys** [comment]
This is handled in the scope of 2.5 and 3.0 releases.
